package cn.blinfra.boot.system.api.errorcode;

import cn.blinfra.boot.system.api.errorcode.dto.ErrorCodeAutoGenerateReqDTO;
import cn.blinfra.boot.system.api.errorcode.dto.ErrorCodeRespDTO;

import java.time.LocalDateTime;
import java.util.List;

/**
 * 错误码 API接口
 */
public interface ErrorCodeApi {

  /**
   * 自动创建错误码
   *
   * @param autoGenerateDTOS 错误码信息
   */
  void autoGenerateErrorCodeList(
    List<ErrorCodeAutoGenerateReqDTO> autoGenerateDTOS
  );

  /**
   * 增量获得错误码数组
   * 如果 minUpdateTime为空时，则获取所有错误码
   *
   * @param applicationName 应用名
   * @param minUpdateTime   最小更新时间
   * @return 错误码数组
   */
  List<ErrorCodeRespDTO> getErrorCodeList(
    String applicationName,
    LocalDateTime minUpdateTime
  );


}
